### ISSUE TITLE
suggestions: Icon Position + 1x

### ISSUE THREAD

**Issue by Darkion43** [belaviyo/volume-booster#4]
hi. i don't have words for the extension its self. Just perfect.

just two suggestions, if is possible:

1) To move the icon just next to volume icon ( or make a optional option for that).

2) add one more option in Shift+click for 1x ( or half of 2x) because some videos is too loud even with 2x.

(Image about Icon Position)
![cscscscscs](https://github.com/belaviyo/volume-booster/assets/117835316/3a96b838-b102-41e9-91c7-3c25f64c7b95)

thank you !!!

**Comment by belaviyo** [comment]
Both issues are fixed. After the next release, you can use a custom CSS selector to change the icon position.
